require('@alipay/appx-compiler/lib/sjsEnvInit.js');
require('./config$.js');
require('../../components/classifyitem/classifyitem.js');
require('../../pages/cart/cart.js');
require('../../pages/index/index.js');
require('../../pages/classify/classify.js');
require('../../pages/classifylist/classifylist.js');
require('../../pages/classifydetail/classifydetail.js');
require('../../pages/confirmorder/confirmorder.js');
